name: Postman API Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
    - main

env:
  FLASK_TESTING: True
  FLASK_APP: app.py:app

jobs:
  postman-API-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10" ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Start app
        run: python -m flask --app app run &
      - name: Run postman collection
        run: |
          postman collection run "${{ github.workspace }}/postman/collections/BetaBrite Tests and Run.json" --integration-id "133347-${{ github.run_id }}"  --env-var ""ecowitt_key=${{ secrets.ECOWITT_KEY }}"" --env-var ""baseUrl=http://127.0.0.1:5000"" --env-var ""ecowitt_app_id=${{ secrets.ECOWITT_APP_ID }}"" --env-var ""ecowitt_mac=${{ secrets.ECOWITT_MAC }}""
